### ISSUE TITLE
CentOS 7 Mirror

### ISSUE THREAD

**Issue by Klaas-** [N3WWN/AzureBuildCentOS#120]
Hi @N3WWN 

there is something wrong with the mirror sync of centos 7

Should have latest:
http://mirror.centos.org/centos/7/updates/x86_64/Packages/sssd-client-1.16.5-10.el7_9.11.x86_64.rpm

Latest on mirror:
http://olcentgbl.trafficmanager.net/centos/7/updates/x86_64/sssd-client-1.16.5-10.el7_9.10.x86_64.rpm

Also being discussed in the centos forum:
https://forums.centos.org/viewtopic.php?f=47&t=78483

**Comment by N3WWN** [comment]
Thanks for the heads up!  I see that there are a couple of mirrors that got out of sync and am manually verifying each one now.

**Comment by N3WWN** [comment]
@Klaas- 

There was one straggler that held on until morning, but it just finished updating. All of the others were up-to-date by about 10p EST last night.

FYI, there were actually two issues, both with the mirroring code, that created the issue. If it had been only one or the other, this would have been resolved about 10 hours earlier. Both of the issues have been addressed and won't be causing further staleness.

Please let me know if you encounter any further issues as I believe everything is resolved at this time.

**Comment by Klaas-** [comment]
Yeah, seems fixed, thank you!
