### ISSUE TITLE
Centos 7 Mirror Packages

### ISSUE THREAD

**Issue by abhigupta1207** [N3WWN/AzureBuildCentOS#122]
Hi Team

We noticed that Centos 7 mirror is not upto date.

Should have latest kernel packages like:
http://mirror.centos.org/centos/7/updates/x86_64/Packages/kernel-3.10.0-1160.62.1.el7.x86_64.rpm

But the open logic mirror is not upto sync.
http://olcentgbl.trafficmanager.net/centos/7/updates/x86_64/kernel-3.10.0-1160.59.1.el7.x86_64.rpm

**Comment by N3WWN** [comment]
Thank you @abhigupta1207 !  

I'm looking into this right now.

**Comment by N3WWN** [comment]
Good news @abhigupta1207 !

I tracked the issue down to a directory permissions problem.  I fixed the permissions and let the systems sync up again overnight.

After checking just now, I can confirm that all of our globally distributed repos are up to date, including the presence of the kernel-3.10.0-1160.62.1.el7.x86_64.rpm package.

**Comment by sudeep1607** [comment]
@N3WWN Does the sync happen daily or on a weekly basis? 

I think the sync is not happening again. CentOS released [kernel-3.10.0-1160.76.1.el7.x86_64.rpm] on 11th august but can't find the same in Open Logic repos yet
