### ISSUE TITLE
CentOS 7 Mirror

### ISSUE THREAD

**Issue by sudeep1607** [N3WWN/AzureBuildCentOS#123]
Hi @N3WWN

There is something wrong with the mirror sync of centos 7. Below packages not synced to the open logic mirror. Could you please check?

Should have latest:
http://mirror.centos.org/centos/7/updates/x86_64/Packages/kernel-3.10.0-1160.80.1.el7.x86_64.rpm

**Comment by N3WWN** [comment]
I'm looking into this right now.  Thanks for letting us know!

**Comment by N3WWN** [comment]
One of our master repos was stale so the Internet-facing repos that sync'd from that master were also stale.  
I'm bringing the master up to date now and will manually trigger the other stale repos to sync as soon as the master is up-to-date.

**Comment by N3WWN** [comment]
Master repo is now up-to-date and Internet-facing repo syncs have started

**Comment by N3WWN** [comment]
The last of the stale Internet-facing repos completed its sync about 20 minutes ago and I have confirmed that all repos contain `kernel-3.10.0-1160.80.1.el7`.
Please let us know if you encounter any additional issues.
