### ISSUE TITLE
OpenLogic CentOS7 updates repo currently not available

### ISSUE THREAD

**Issue by juan-castrillon** [N3WWN/AzureBuildCentOS#124]
Hello. Starting from yesterday, I am not able to deploy new machines which in some point call the `yum update` command. There appears to be a problem relating to the package repo similar to #108 

Here are some logs of what happens when I try to install/update some packages: 

```
Downloading packages:
http://olcentgbl.trafficmanager.net/centos/7/updates/x86_64/java-1.8.0-openjdk-headless-1.8.0.352.b08-2.el7_9.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article
https://wiki.centos.org/yum-errors
If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
http://olcentgbl.trafficmanager.net/centos/7/os/x86_64/libxslt-1.1.28-6.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://olcentgbl.trafficmanager.net/centos/7/os/x86_64/lksctp-tools-1.0.17-2.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://olcentgbl.trafficmanager.net/centos/7/os/x86_64/pcsc-lite-libs-1.8.8-8.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://olcentgbl.trafficmanager.net/centos/7/os/x86_64/python-lxml-3.2.1-4.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Error downloading packages:
  1:java-1.8.0-openjdk-headless-1.8.0.352.b08-2.el7_9.x86_64: [Errno 256] No more mirrors to try.
  libxslt-1.1.28-6.el7.x86_64: [Errno 256] No more mirrors to try.
  python-lxml-3.2.1-4.el7.x86_64: [Errno 256] No more mirrors to try.
  pcsc-lite-libs-1.8.8-8.el7.x86_64: [Errno 256] No more mirrors to try.
  lksctp-tools-1.0.17-2.el7.x86_64: [Errno 256] No more mirrors to try.
```

Thanks in advance for any help :smile:

**Comment by N3WWN** [comment]
Thank you for the report @juan-castrillon !

We added 2 additional repo nodes to our West Europe cluster yesterday which appear to have missing packages.  These are the only nodes in any of our global regions which are missing packages.

I've removed these two nodes from the load balancer until I can get them sync'd properly.

Sorry for the inconvenience...

**Comment by N3WWN** [comment]
@juan-castrillon I confirmed that the re-sync of the two new nodes was complete and just added those two nodes back into the load balancer.

Please let us know if you have any further issues.

Thanks!
